INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Poochie", "perro", "2021-07-31");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Doggi", "perro", "2019-10-07");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Neron", "perro", "2021-12-31");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Birdie", "canario", "2020-05-14");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Piolin", "canario", "2021-09-01");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Canito", "perro", "2021-07-31");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Jake", "perro", "2022-01-03");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Lassie", "perro", "2020-08-13");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Proser", "perro", "2021-04-04");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Wishbone", "perro", "2019-12-16");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Ranger", "perro", "2020-09-02");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Shasha", "gato", "2022-01-03");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Nago", "gato", "2021-10-13");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Michi", "gato", "2019-02-03");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Cheshire", "gato", "2022-11-24");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Alvina", "gato", "2020-08-30");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Neko", "gato", "2021-03-03");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Shalquoir", "gato", "2020-12-10");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Parry", "loro", "2020-05-14");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Taca", "loro", "2021-05-20");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Pancho", "loro", "2019-07-24");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Hamtaro", "hamster", "2021-12-04");
INSERT INTO SistemaGerencial_paciente (nombrePac, especie, fechaInscrip) VALUES ("Hammie", "hamster", "2020-05-14");

INSERT INTO SistemaGerencial_clinica (nombreCli, propietario) VALUES ("Pets", "José Antonio");
INSERT INTO SistemaGerencial_clinica (nombreCli, propietario) VALUES ("Amigos Peludos", "Andrew Pérez");
INSERT INTO SistemaGerencial_clinica (nombreCli, propietario) VALUES ("Huellitas", "Maria Celia");
