# Generated by Django 3.2.4 on 2022-05-24 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaGerencial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='medico',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
