# Generated by Django 3.2.4 on 2022-06-03 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaGerencial', '0002_bitacora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='nomPersona',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='nomUsuario',
        ),
        migrations.RemoveField(
            model_name='bitacora',
            name='usuarioId',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SistemaGerencial.user'),
            preserve_default=False,
        ),
    ]
