# Generated by Django 3.2.4 on 2022-05-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaGerencial', '0002_clinica_consulta_consultorio_paciente_vacuna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaGerencial.clinica')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SistemaGerencial.consultorio')),
                ('paciente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='SistemaGerencial.paciente')),
            ],
        ),
    ]
