# Generated by Django 3.2.4 on 2022-05-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SistemaGerencial', '0003_auto_20220524_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacuna',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='SistemaGerencial.consultorio'),
            preserve_default=False,
        ),
    ]
